### ISSUE TITLE
Clarify guidance on SPF null records for zones that send no email

### ISSUE THREAD

**Issue by konklone** [dhs-ncats/cyber.dhs.gov#11]
https://cyber.dhs.gov/guide/#what-should-be-done-with-domains-that-do-not-send-mail says:

> With DMARC p=reject, it is not necessary to specify SPF “null records” on every active domain in the zone, though doing so is not harmful.

This section is ambiguous on whether SPF null records should be set on the parent domain (the root of the zone). 

For a domain like `gsatest1.gov`, for example, which sends no email and acts as a testing area, what are the minimum records necessary, from both a compliance and security standpoint?

**Comment by h-m-f-t** [comment]
The quick answer is that a null SPF record should be added to the second-level domain. 

There are more things an organization can do, as described by this [M3AAWG document](https://www.m3aawg.org/sites/default/files/m3aawg_parked_domains_bp-2015-12.pdf) that gives best current practices (from 2015) on this very thing. We're going to see about following up with them and/or running some tests.

I may be wrong, but I don't have a ton of faith in all the recommendations, especially the CNAMEing and wildcarding ones, given they are are not described in the DMARC or SPF RFCs, so clients seem unlikely to universally check at a wildcard.

**Comment by konklone** [comment]
Would a PR adding that quick answer to the FAQ section be welcome/

**Comment by AntiFreeze** [comment]
We had some debate over wildcarding when writing the M3AAWG SPF best practices document (https://www.m3aawg.org/sites/default/files/m3aawg_managing-spf_records-2017-08.pdf). Ultimately, we decided to not mention wildcarding because it is recommended against in the RFC: https://tools.ietf.org/html/rfc7208#section-3.5

Beyond that, all the major ISPs treat SPF records differently (except when coupled with DMARC at enforcement), except for the SPF null record which is a strong signal that no email is ever legitimate for the domain.

Remember, some ISPs override DMARC failures because of forwarding (which won't stop until ARC adoption is widespread), and the SPF null record is the only way to tell them not to do this (although to be very clear, even this doesn't always matter, but it helps).

For these reasons, I agree with the above suggestion that advice in the compliance guide be updated to strongly recommend an SPF null record on non-sending domains no matter what.

**Comment by h-m-f-t** [comment]
Thanks for the suggestion, @AntiFreeze!

>I agree with the above suggestion that advice in the compliance guide be updated to strongly recommend an SPF null record on non-sending domains

Is your sense that this advice applies to more than non-mail-sending _second-level domains_, i.e.,  to all subdomains, too? Part of the goal in getting to `p=reject` for every second-level domain is that all subdomains are protected, too (as long as there isn't a lower-than-reject `sp` directive).

**Comment by AntiFreeze** [comment]
So unfortunately, there is no good guidance with regards to SPF and subdomain hierarchy. Since the RFC explicitly discourages wildcarding, the recommendation is to put a null record and p=reject on every second-level domain.

Exactly because of this issue, there was actually an ORT (open round table) at M3AAWG41 last month which asked the question of if SPF needed a fallback to organizational domain policy the way DMARC does. I'm uncertain where this conversation ended, and I'll inquire. Regardless, any output from this is months (if not years) away from any practical standard or advice.
